### PR TITLE
converted hard-coded data into json, fix #1

### LINKED ISSUE #1: Creating ORGANICCHEMISTRY.py and adding recent pyqs to it in the format defined in readme

### PR DESCRIPTION
**Pull request by sujaldev**
This format will be able to support multiple answer questions

### CODE REVIEW

**Comment by sujaldev** [comment]
This format can support multiple answer questions.

**Comment by sujaldev** [comment]
I'm adding a commit to use this new model but I don't know supabase, I tried to create a dev environment and it works, except it's not registering the comments it has already responded to so please check for that issue for merging.

**Comment by TriAay249** [comment]
Are you sure your code is correct? I tried running a test through repl.it and I got an error 
`line 51, in alphabetic_solutions
    return solution_string.removesuffix(", ")
AttributeError: 'str' object has no attribute 'removesuffix`

**Comment by sujaldev** [comment]
What python version are you using? removesuffix is a new method...

**Comment by TriAay249** [comment]
repl.it uses 3.8.12 . So either we need a new hosting site or older methods

**Comment by TriAay249** [comment]
OK. With Backwards compatibility, The Replies are generated perfectly and supabase seems to receive the entries as well. I will merge the code

**Comment by sujaldev** [comment]
Is the bot down? I tried commenting, no replies

**Comment by TriAay249** [comment]
I had to turn it down for a while . The new code I ran started an infinite loop even though the database was getting updated . For now , I have turned it back on with the old code , till the loop gets solved @sujaldev

**Comment by sujaldev** [comment]
Should we have a discord server for better collaboration?

**Comment by TriAay249** [comment]
Sure.

**Comment by TriAay249** [comment]
There was some error with the repl.it code. The bot should now work with the new code without giving infinite loops
@sujaldev

**Comment by sujaldev** [comment]
> Sure.

So are you creating or should I?

> There was some error with the repl.it code. The bot should now work with the new code without giving infinite loops
@sujaldev

I think there might be a bug, newlines aren't being recognized.

**Comment by TriAay249** [comment]
I believe it is working now ?

**Comment by sujaldev** [comment]
I think I added newlines between the "here is a pyq for ya" line and the actual question and then the solution but the bot doesn't seem to be obeying that.

**Comment by TriAay249** [comment]
You need multiple new lines for one to be displayed . Weird but that somehow works

**Comment by sujaldev** [comment]
I realise that, its a standard markdown feature and I have obeyed that rule, see here:

https://github.com/TriAay249/JEEPYQREPLYBOT/blob/b66b66f594f93c27c479bb7db867bd5056911107/data_api.py#L16-L28

But I have no clue why it's still not working.

**Comment by sujaldev** [comment]
Yep working perfectly now! Do you think we should move away from repl.it to dokku for more control?

**Comment by TriAay249** [comment]
Rather move the completed version over

**Pull request merged**
